// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef fl_firmata_h
#define fl_firmata_h
#include <FL/Fl.H>
#include "Fl_Pin_Table.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>

class help_about {
public:
  help_about();
  Fl_Double_Window *help_win;
  Fl_Output *web;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  void show();
};
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>

class fl_firmata {
public:
  fl_firmata();
  Fl_Double_Window *firmata_win;
  Fl_Pin_Table *pin_table;
  Fl_Button *connect;
private:
  inline void cb_connect_i(Fl_Button*, void*);
  static void cb_connect(Fl_Button*, void*);
public:
  Fl_Button *discon;
private:
  inline void cb_discon_i(Fl_Button*, void*);
  static void cb_discon(Fl_Button*, void*);
  inline void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
  inline void cb_About_i(Fl_Button*, void*);
  static void cb_About(Fl_Button*, void*);
public:
  Fl_Choice *port_choice;
private:
  inline void cb_port_choice_i(Fl_Choice*, void*);
  static void cb_port_choice(Fl_Choice*, void*);
public:
  Fl_Box *status_bar;
  void show();
  void quit();
  void add_pin(int pin, pin_t pint);
  static void on_idle_window(void *userdata);
};
#endif
